export const WILAYA_COMMUNES: Record<string, string[]> = {
  Alger: [
    "Toutes les communes",
    "Hydra (Affaires / Ambassades)",
    "Sidi Yahia",
    "Dely Ibrahim",
    "Chéraga",
    "Bab Ezzouar (Centre d'Affaires)",
    "Kouba",
    "El Biar",
    "Bir Mourad Raïs",
    "Saïd Hamdine",
    "Bordj El Kiffan",
    "Bordj El Bahri",
    "Zéralda",
    "Draria",
    "Ben Aknoun",
    "Rouïba (Zone Industrielle)",
    "Oued Smar (Zone Industrielle)",
    "Hussein Dey",
    "Belouizdad",
    "Alger-Centre",
    "Staouéli / Club des Pins",
    "Aïn Benian",
    "Baraki",
  ],
  Oran: [
    "Toutes les communes",
    "Akid Lotfi",
    "Maraval",
    "Es Senia (Zone Industrielle)",
    "Bir El Djir",
    "Canastel",
    "Oran-Centre",
    "Courbet",
    "Gambetta",
    "Aïn El Turk",
    "Arzew (Zone Industrielle)",
  ],
  Constantine: [
    "Toutes les communes",
    "Ali Mendjeli (Nouvelle Ville)",
    "Constantine-Centre",
    "El Khroub",
    "Didouche Mourad",
    "Aïn Smara",
  ],
  Sétif: [
    "Toutes les communes",
    "Sétif-Centre",
    "El Eulma (Grand Marché Dubaï)",
    "Aïn Arnat",
    "Aïn Oulmène",
  ],
  Blida: [
    "Toutes les communes",
    "Blida-Centre",
    "Boufarik",
    "Ouled Yaïch",
    "Larbaâ",
    "Béni Mered",
  ],
  Annaba: [
    "Toutes les communes",
    "Annaba-Centre",
    "El Bouni",
    "Sidi Amar",
    "El Hadjar (Zone Industrielle)",
  ],
  Béjaïa: [
    "Toutes les communes",
    "Béjaïa-Centre",
    "Akbou (Zone Industrielle)",
    "El Kseur",
    "Tichy",
  ],
  Tlemcen: [
    "Toutes les communes",
    "Tlemcen-Centre",
    "Mansourah",
    "Maghnia",
    "Chetouane",
  ],
  Batna: [
    "Toutes les communes",
    "Batna-Centre",
    "Barika",
    "Ain Touta",
  ],
  Mostaganem: [
    "Toutes les communes",
    "Mostaganem-Centre",
    "Ain Tedeles",
    "Sidi Lakhdar",
  ],
};

export const SECTOR_SUBCATEGORIES: Record<string, { label: string; query: string }[]> = {
  "Cabinet médical": [
    { label: "Toutes spécialités médicales", query: "médical" },
    { label: "Cliniques Médico-Chirurgicales", query: "clinique médicale chirurgicale" },
    { label: "Cabinets Dentaires & Orthodontie", query: "dentiste cabinet dentaire" },
    { label: "Laboratoires d'Analyses Médicales", query: "laboratoire analyse médicale" },
    { label: "Centres d'Ophtalmologie & Yeux", query: "ophtalmologue ophtalmologie" },
    { label: "Pharmacies & Parapharmacies", query: "pharmacie parapharmacie" },
    { label: "Centres d'Imagerie & Radiologie (IRM)", query: "radiologie scanner irm" },
    { label: "Pédiatrie & Gynécologie", query: "pédiatre gynécologue cabinet" },
  ],
  Industrie: [
    { label: "Tous types industriels", query: "industrie" },
    { label: "Grossistes & Distributeurs", query: "grossiste distribution" },
    { label: "Importateurs & Négociants", query: "import export négoce" },
    { label: "Matériaux de Construction & BTP", query: "matériaux construction quincaillerie gros" },
    { label: "Pièces de Rechange Automobile", query: "pièces détachées rechange automobile" },
    { label: "Agroalimentaire en Gros", query: "grossiste agroalimentaire alimentation" },
    { label: "Plastique, Chimie & Emballage", query: "emballage plastique usine" },
  ],
  Immobilier: [
    { label: "Tous types immobilier", query: "immobilier" },
    { label: "Agences Immobilières", query: "agence immobiliere transaction" },
    { label: "Promoteurs Immobiliers", query: "promoteur immobilier promotion immobiliere" },
    { label: "Entreprises BTP & Travaux", query: "entreprise batiment btp construction" },
    { label: "Bureaux d'Architecture & Ingénierie", query: "architecte bureau etudes ingenierie" },
  ],
  Hôtel: [
    { label: "Tous types d'hôtellerie", query: "hotel" },
    { label: "Hôtels 3 & 4 étoiles", query: "hotel residence etoiles" },
    { label: "Hôtels d'Affaires & Aéroports", query: "hotel affaires business" },
    { label: "Complexes & Résidences Touristiques", query: "residence touristique complexe" },
  ],
  Restaurant: [
    { label: "Tous types de restauration", query: "restaurant" },
    { label: "Restaurants Gastronomiques", query: "restaurant gastronomique" },
    { label: "Pizzerias & Fast-Foods", query: "pizzeria fast food burger" },
    { label: "Salons de Thé & Coffee Shops", query: "salon de the cafe restaurant" },
    { label: "Traiteurs & Salles d'Événements", query: "traiteur patisserie evenement" },
  ],
  Beauté: [
    { label: "Tous types de beauté", query: "beauté" },
    { label: "Salons de Coiffure & Esthétique", query: "salon coiffure institut beaute" },
    { label: "Parfumeries & Cosmétique", query: "cosmetique parfumerie maquillage" },
    { label: "Spas, Hammams & Bien-être", query: "spa hammam bien etre massage" },
  ],
  "Éducation / Formation": [
    { label: "Tous types d'éducation", query: "école" },
    { label: "Écoles Privées (Primaire, Collège, Lycée)", query: "ecole privee primaire lycee" },
    { label: "Centres de Formation Professionnelle", query: "centre formation professionnelle cours" },
    { label: "Écoles de Langues & Informatique", query: "ecole langues cours anglais" },
    { label: "Crèches & Garderies Maternelles", query: "creche garderie maternelle" },
  ],
  Voyage: [
    { label: "Tous types de voyages", query: "voyage" },
    { label: "Agences de Voyages & Tourisme", query: "agence voyage tourisme billets" },
    { label: "Agences Omra & Hadj", query: "agence omra hadj visa" },
  ],
  "E-commerce": [
    { label: "Tous types de commerces", query: "boutique" },
    { label: "Showrooms Meubles & Literie", query: "showroom meuble decoration maison" },
    { label: "Électroménager & Informatique", query: "electromenager informatique high tech" },
    { label: "Boutiques Prêt-à-porter & Mode", query: "boutique vetements pret a porter mode" },
  ],
  "Autre prestation": [
    { label: "Tous types de prestations", query: "entreprise" },
    { label: "Salles des Fêtes & Mariages", query: "salle des fetes evenement mariage" },
    { label: "Cabinets d'Avocats & Juridique", query: "avocat cabinet juridique notaire" },
    { label: "Experts Comptables & Commissaires", query: "expert comptable commissaire aux comptes" },
    { label: "Agences de Communication & Marketing", query: "agence communication publicite marketing" },
  ],
};
